version: '3'
services:
    pizza-store:
        image: pizza-store:1.0
        ports:
            - 8081:8081
        depends_on:
            - mongodb
        environment:
             SPRING_DATA_MONGODB_URI: mongodb://mongodb/pizza-store
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        ports:
            - 27017:27017
        command: mongod --smallfiles