version: '2'
services:
    pizza-store:
        image: pizza-store/server:latest
        ports:
            - 8081:8081
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        ports:
            - 27017:27017
        command: mongod --smallfiles