package pl.bk.pizza.store.domain.exception;

public enum ErrorCode
{
    UNPROCESSABLE_PRODUCT_DTO_TYPE,
    UNPROCESSABLE_PRODUCT_TYPE,
    EMPTY_PRODUCT_INFO,
    EMPTY_PIZZA_SIZE,
    EMPTY_DOUGH,
    EMPTY_KEBAB_DESCRIPTION,
    EMPTY_KEBAB_NAME,
    EMPTY_PIZZA_TOPPING_NAME,
    EMPTY_USER_EMAIL,
    INVALID_EMAIL,
    EMPTY_TELEPHONE_NUMBER,
    EMPTY_ADDRESS,
    EMPTY_USER_NAME,
    EMPTY_USER_SURNAME,
    EMPTY_CITY,
    EMPTY_STREET,
    EMPTY_STREET_NUMBER,
    EMPTY_POSTCODE,
    EMPTY_NUMBER,
    MISSING_ORDER,
    MISSING_PRODUCT,
    MISSING_USER,
    USER_EXISTS,
    EMPTY_PRODUCT_PRICE,
    INTERNAL_ERROR;
}
